### ISSUE TITLE
Firmware update of Seagate

### ISSUE THREAD

**Issue by bnote** [jandelgado/general#1]
Re: [Firmware update of Seagate harddisk using Linux](https://github.com/jandelgado/general/wiki/Firmware-update-of-Seagate-harddisk-using-Linux) 

Hello. Thank you for very useful info.
Is there a similar way to dump current firmware from the ST HDD?
.

**Comment by jandelgado** [comment]
Sorry - I've now experience with that. Perhaps the hdparm command supports it.

**Comment by bnote** [comment]
ST released recently their big bundle [SeaChest](https://github.com/Seagate/ToolBin/tree/master/SeaChest) for Linux and Windows. 
But there is no dump utility :( .... 
Look on it. Perhaps you find some usefful or simple interesting things.
.
